<div class="product-form-grid">
    <div class="form-group"><label class="form-label" for="code">Kode Produk *</label><input class="form-control @error('code') is-invalid @enderror" id="code" name="code" type="text" minlength="2" maxlength="40" required value="{{ old('code', $product->code ?? '') }}" placeholder="PST-001">@error('code')<span class="form-error">{{ $message }}</span>@enderror</div>
    <div class="form-group"><label class="form-label" for="barcode">Barcode</label><input class="form-control @error('barcode') is-invalid @enderror" id="barcode" name="barcode" type="text" maxlength="100" value="{{ old('barcode', $product->barcode ?? '') }}" placeholder="Contoh: 001234567890">@error('barcode')<span class="form-error">{{ $message }}</span>@enderror</div>
    <div class="form-group product-form-grid__wide"><label class="form-label" for="name">Nama Produk *</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" type="text" maxlength="255" required value="{{ old('name', $product->name ?? '') }}">@error('name')<span class="form-error">{{ $message }}</span>@enderror</div>
    <div class="form-group"><label class="form-label" for="brand">Merek</label><input class="form-control @error('brand') is-invalid @enderror" id="brand" name="brand" type="text" maxlength="150" value="{{ old('brand', $product->brand ?? '') }}">@error('brand')<span class="form-error">{{ $message }}</span>@enderror</div>
    <div class="form-group"><label class="form-label" for="size">Ukuran/Kemasan</label><input class="form-control @error('size') is-invalid @enderror" id="size" name="size" type="text" maxlength="100" value="{{ old('size', $product->size ?? '') }}" placeholder="Contoh: 500 ml">@error('size')<span class="form-error">{{ $message }}</span>@enderror</div>
    <div class="form-group"><label class="form-label" for="category_id">Kategori *</label><select class="form-control @error('category_id') is-invalid @enderror" id="category_id" name="category_id" required><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int) old('category_id', $product->category_id ?? 0) === $category->id)>{{ $category->name }}{{ isset($category->is_active) && !$category->is_active ? ' (Nonaktif—dipertahankan)' : '' }}</option>@endforeach</select>@error('category_id')<span class="form-error">{{ $message }}</span>@enderror</div>
    <div class="form-group"><label class="form-label" for="unit_id">Satuan Jual *</label><select class="form-control @error('unit_id') is-invalid @enderror" id="unit_id" name="unit_id" required><option value="">Pilih satuan</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected((int) old('unit_id', $product->unit_id ?? 0) === $unit->id)>{{ $unit->name }}{{ $unit->symbol ? ' ('.$unit->symbol.')' : '' }}{{ isset($unit->is_active) && !$unit->is_active ? ' — Nonaktif, dipertahankan' : '' }}</option>@endforeach</select>@error('unit_id')<span class="form-error">{{ $message }}</span>@enderror</div>
</div>
