<section class="table-card" aria-label="Daftar produk"><div class="table-wrapper"><table class="table product-table">
    <thead><tr><th>Produk</th><th>Identitas</th><th>Kategori</th><th>Satuan</th>@if($isOwner)<th>Harga Beli</th>@endif<th>Harga Jual</th><th>Status</th><th>Diperbarui</th><th class="table-actions">Aksi</th></tr></thead>
    <tbody>@forelse($products as $product)<tr>
        <td><div class="product-cell"><img class="product-thumbnail" src="{{ $product->image_path ? asset('storage/'.$product->image_path) : asset('assets/images/placeholders/product-placeholder.svg') }}" alt=""><span><strong>{{ $product->name }}</strong><small>{{ $product->brand ?: 'Tanpa merek' }}{{ $product->size ? ' · '.$product->size : '' }}</small></span></div></td>
        <td><strong>{{ $product->code }}</strong><small class="table-secondary">{{ $product->barcode ?: 'Tanpa barcode' }}</small></td><td>{{ $product->category->name }}</td><td>{{ $product->unit->symbol ?: $product->unit->name }}</td>
        @if($isOwner)<td>{{ \App\Support\Format\Rupiah::format($product->purchase_price) }}</td>@endif
        <td><strong>{{ \App\Support\Format\Rupiah::format($product->selling_price) }}</strong></td><td><span class="badge {{ $product->is_active ? 'badge-success' : 'badge-danger' }}">{{ $product->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td>{{ $product->updated_at->format('d M Y') }}</td>
        <td class="table-actions"><div class="action-group"><a class="btn btn-sm btn-outline" href="{{ route('products.show', $product) }}">Detail</a><a class="btn btn-sm btn-secondary" href="{{ route('products.edit', $product) }}">Edit</a><a class="btn btn-sm btn-outline" href="{{ route('products.price-history.index', $product) }}">Riwayat</a><button class="btn btn-sm {{ $product->is_active ? 'btn-danger' : 'btn-success' }}" type="button" data-product-status data-action="{{ route('products.status.update', $product) }}" data-name="{{ $product->name }}" data-next-status="{{ $product->is_active ? '0' : '1' }}">{{ $product->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></div></td>
    </tr>@empty<tr class="table-empty-row"><td colspan="{{ $isOwner ? 9 : 8 }}">Tidak ada produk yang sesuai dengan filter.</td></tr>@endforelse</tbody>
</table></div><div class="table-pagination"><span>Menampilkan {{ $products->firstItem() ?? 0 }}–{{ $products->lastItem() ?? 0 }} dari {{ $products->total() }}</span><nav class="pagination-buttons" aria-label="Pagination produk">@if($products->onFirstPage())<span class="pagination-button" aria-disabled="true">‹</span>@else<a class="pagination-button" href="{{ $products->previousPageUrl() }}">‹</a>@endif<span class="pagination-button is-active">{{ $products->currentPage() }}</span>@if($products->hasMorePages())<a class="pagination-button" href="{{ $products->nextPageUrl() }}">›</a>@else<span class="pagination-button" aria-disabled="true">›</span>@endif</nav></div></section>
